version: '3'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    image: shortlink_api
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_PORT: ${APP_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      ORIGIN_URL: ${ORIGIN_URL}
      
    depends_on:
      - postgres  # Menggunakan hanya layanan tanpa indeks
    links:
      - postgres  # Menggunakan layanan dengan indeks
    # command: ["./wait-for-it.sh", "postgres:5432", "postgres up"]

